{% set name = "pcmdi_metrics" %}
{% set version = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PCMDI/pcmdi_metrics/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - compositeDiurnalStatistics.py = pcmdi_metrics.diurnal.scripts.compositeDiurnalStatistics:main
    - computeStdOfDailyMeans.py = pcmdi_metrics.diurnal.scripts.computeStdOfDailyMeans:main
    - fourierDiurnalAllGrid.py = pcmdi_metrics.diurnal.scripts.fourierDiurnalAllGrid:main
    - fourierDiurnalGridpoints.py = pcmdi_metrics.diurnal.scripts.fourierDiurnalGridpoints:main
    - savg_fourier.py = pcmdi_metrics.diurnal.scripts.savg_fourier:main
    - std_of_dailymeans.py = pcmdi_metrics.diurnal.scripts.std_of_dailymeans:main
    - std_of_hourlyvalues.py = pcmdi_metrics.diurnal.scripts.std_of_hourlyvalues:main
    - std_of_meandiurnalcycle.py = pcmdi_metrics.diurnal.scripts.std_of_meandiurnalcycle:main

requirements:
  build:
    - python 3.6
    - numpy 2.0
  host:
    - python 3.6
    - pip
    - setuptools    
  run:
    - python >=3.6
    - cdms2
    - genutil
    - cdutil
    - cdp
    - matplotlib-base
    - numpy >=2.0.0,<3.0.0
    - cartopy
    - cmocean
    - colorcet
    - eofs >=2.0.0
    - jupyterlab
    - nb_conda
    - nb_conda_kernels
    - nc-time-axis
    - notebook <7.0.0
    - numdifftools
    - enso_metrics
    - seaborn
    - netcdf4
    - regionmask
    - rasterio
    - shapely
    - xmltodict
    - xcdat  >=0.7.3

test:
  requires:
    - python 3.6
  imports:
    - pcmdi_metrics
  commands:
    - mean_climate_driver.py --help
    - mpindex_compute.py --help
    - driver_monsoon_sperber.py --help
    - std_of_dailymeans.py --help
    - variability_modes_driver.py --help
    - mjo_metrics_driver.py --help
    - enso_driver.py --help
    - variability_across_timescales_PS_driver.py --help
    - precip_distribution_driver.py --help
    - extremes_driver.py --help
    - sea_ice_driver.py --help

about:
  home: http://github.com/PCMDI/pcmdi_metrics
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: The PCMDI metrics package is used to objectively compare results from climate models with observations using well-established statistical tests. Results are produced in the context of all model simulations contributed to CMIP5 and earlier CMIP phases. Among other purposes, this enables modeling groups to evaluate
    changes during the development cycle in the context of the structural error distribution of the multi-model ensemble. Currently, the comparisons are focused on large- to global-scale annual cycle performance metrics.
  description: model metrics tools
  doc_url: https://pcmdi.github.io/pcmdi_metrics/
  dev_url: https://github.com/PCMDI/pcmdi_metrics

extra:
  recipe-maintainers:
    - acordonez
    - lee1043
    - gleckler1
