{% set name = "pcmdi_metrics" %}
{% set version = "3.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PCMDI/pcmdi_metrics/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 3f66df9b0d0adec3b015ece951c47b982b46126e0220823f4a6cdce0dee5d8b7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - compositeDiurnalStatistics.py = pcmdi_metrics.diurnal.scripts.compositeDiurnalStatistics:main
    - computeStdOfDailyMeans.py = pcmdi_metrics.diurnal.scripts.computeStdOfDailyMeans:main
    - fourierDiurnalAllGrid.py = pcmdi_metrics.diurnal.scripts.fourierDiurnalAllGrid:main
    - fourierDiurnalGridpoints.py = pcmdi_metrics.diurnal.scripts.fourierDiurnalGridpoints:main
    - savg_fourier.py = pcmdi_metrics.diurnal.scripts.savg_fourier:main
    - std_of_dailymeans.py = pcmdi_metrics.diurnal.scripts.std_of_dailymeans:main
    - std_of_hourlyvalues.py = pcmdi_metrics.diurnal.scripts.std_of_hourlyvalues:main
    - std_of_meandiurnalcycle.py = pcmdi_metrics.diurnal.scripts.std_of_meandiurnalcycle:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - cdms2
    - genutil
    - cdutil
    - cdp
    - matplotlib-base
    - numpy >=2.0.0,<3.0.0
    - cartopy
    - cmocean
    - colorcet
    - eofs
    - jupyterlab
    - nb_conda
    - nb_conda_kernels
    - nc-time-axis
    - notebook <7.0.0
    - numdifftools
    - enso_metrics
    - seaborn
    - netcdf4
    - regionmask
    - rasterio
    - shapely
    - xmltodict
    - xcdat >=0.6.1
    - xclim

test:
  requires:
    - python {{ python_min }}
  imports:
    - pcmdi_metrics
  commands:
    - mean_climate_driver.py --help
    - mpindex_compute.py --help
    - driver_monsoon_sperber.py --help
    - std_of_dailymeans.py --help
    - variability_modes_driver.py --help
    - mjo_metrics_driver.py --help
    - enso_driver.py --help
    - variability_across_timescales_PS_driver.py --help
    - precip_distribution_driver.py --help
    - extremes_driver.py --help
    - sea_ice_driver.py --help

about:
  home: http://github.com/PCMDI/pcmdi_metrics
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: The PCMDI metrics package is used to objectively compare results from climate models with observations using well-established statistical tests. Results are produced in the context of all model simulations contributed to CMIP5 and earlier CMIP phases. Among other purposes, this enables modeling groups to evaluate
    changes during the development cycle in the context of the structural error distribution of the multi-model ensemble. Currently, the comparisons are focused on large- to global-scale annual cycle performance metrics.
  description: model metrics tools
  doc_url: https://pcmdi.github.io/pcmdi_metrics/
  dev_url: https://github.com/PCMDI/pcmdi_metrics

extra:
  recipe-maintainers:
    - acordonez
    - lee1043
    - gleckler1
